import {
  CloudUpload,
  Image,
  Lock,
  Monitor,
  Settings,
  Star,
} from "lucide-react";

const features = [
  {
    name: "Instant Image Generation",
    description:
      "Imagine Space turns your ideas into stunning visuals in seconds. Leverage the power of AI to bring your creative vision to life without the need for complex tools. Simply enter your prompt and watch your imagination unfold.",
    icon: Image,
  },
  {
    name: "Secure User Access",
    description:
      "Sign in with confidence using Google and GitHub authentication. Your account and generated images are protected with the highest standards of security, ensuring a safe and seamless experience.",
    icon: Lock,
  },
  {
    name: "High-Quality Outputs",
    description:
      "Get high-definition, detailed images generated by cutting-edge AI technology. Whether for design, marketing, or personal projects, Imagine Space ensures your results meet the highest quality standards.",
    icon: Monitor,
  },
  {
    name: "Customizable Prompts",
    description:
      "Craft the perfect image by refining your prompts. With the ability to specify themes, styles, and objects, Imagine Space gives you the flexibility to generate the exact visual you're imagining.",
    icon: Settings,
  },
  {
    name: "Explore Infinite Possibilities",
    description:
      "The more you explore, the more creative possibilities open up. Experiment with different styles, moods, and designs to create unique visuals that inspire and impress.",
    icon: Star,
  },
  {
    name: "Fast, Real-Time Generation",
    description:
      "Experience real-time image generation, where the AI processes your requests quickly and efficiently. No more waiting—your visual ideas come to life instantly, allowing you to iterate and refine your concepts on the fly.",
    icon: CloudUpload,
  },
];

export function Features() {
  return (
    <div className="py-18">
      <div className="max-w-2xl mx-auto px-4 py-12 bg-transparent backdrop-blur-0 supports-[backdrop-filter]:bg-transparent">
        <div className="text-center">
          <p className="text-xl font-semibold text-purple-600 mb-3">
            Unleash Your Creativity
          </p>
          <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl mb-6">
            Transform Your Ideas into Art!
          </h1>
          <p className="text-lg leading-8 text-muted-foreground">
            With Imagine Space, the creative possibilities are endless. Generate
            breathtaking visuals in an instant with just a few clicks. Start
            your creative journey now!
          </p>
        </div>
      </div>
      <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-4xl">
        <div className="grid max-w-xl gap-x-8 gap-y-10 lg:max-w-none lg:grid-cols-2 lg:gap-y-16">
          {features.map((feature) => (
            <div key={feature.name} className="relative pl-16">
              <div className="text-base font-medium leading-7">
                <div className="absolute left-0 top-0 flex size-10 items-center justify-center rounded-lg bg-purple-950">
                  <feature.icon className="size-6 text-purple-400" />
                </div>
                {feature.name}
              </div>
              <p className="mt-2 text-sm text-muted-foreground leading-snug">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
