-- =============================================================================
-- ImagineSpace — public schema only (from old Supabase backup)
-- Run this in: Supabase Dashboard → SQL Editor → New query
--
-- Do NOT run the full cluster dump on hosted Supabase — it will fail or break
-- managed auth/storage/realtime. Only recreate your app tables in `public`.
--
-- Your backup used TEXT for canvas_id / user_id (UUIDs stored as strings). This
-- matches what the Next.js app sends.
-- =============================================================================

-- Optional: remove old tables if you created different versions first
-- DROP TABLE IF EXISTS public.images_edited CASCADE;
-- DROP TABLE IF EXISTS public.images_created CASCADE;
-- DROP TABLE IF EXISTS public.subscriptions CASCADE;
-- DROP TABLE IF EXISTS public.canvas CASCADE;

CREATE TABLE IF NOT EXISTS public.canvas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  canvas_id text,
  user_id text
);

CREATE TABLE IF NOT EXISTS public.images_created (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  canvas_id text,
  user_id text,
  prompt text,
  url text,
  filter text
);

CREATE TABLE IF NOT EXISTS public.images_edited (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  canvas_id text,
  url text,
  caption text,
  user_id text
);

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id text,
  sub_id text
);

-- Grant API roles (default on new Supabase projects, safe to re-run)
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE public.canvas TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE public.images_created TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE public.images_edited TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE public.subscriptions TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Optional: seed OLD data from your backup (canvas / images / subscriptions).
-- Your NEW login will get a NEW auth.users id — old user_id values will NOT match
-- unless you migrate Auth users (advanced). Only run these if you understand that.
-- -----------------------------------------------------------------------------
/*
INSERT INTO public.canvas (id, created_at, canvas_id, user_id) VALUES
  (12, '2024-11-11 14:35:26.598558+00', 'dfed4355-b2cd-4840-a1a6-9fb459c974bd', '5248a83a-5555-4138-8837-0065035287c0'),
  (13, '2024-11-11 14:51:15.863091+00', '177e6d3e-4d84-469a-9bdf-a95106df57c7', '5248a83a-5555-4138-8837-0065035287c0'),
  (14, '2024-11-18 07:03:01.99541+00', '18e186cc-c12f-4b3e-b597-c4f8b3fd0af1', '33b4712b-6b46-4f13-a621-ebe5aab4b6d6');

SELECT setval(pg_get_serial_sequence('public.canvas', 'id'), (SELECT MAX(id) FROM public.canvas));

-- … add images_created / images_edited / subscriptions COPY rows similarly if needed.
*/
